name: Generate terraform docs
on:
  - push

jobs:
  docs:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - uses: hashicorp/setup-terraform@v3

    - name: Setup Graphviz
      uses: ts-graphviz/setup-graphviz@v2

    - name: Generate Terraform graph
      run: | 
        terraform init
        terraform graph | dot -Tpng >../visuals/terraform-graph.png
      shell: bash
      working-directory: terraform

    - name: Render terraform docs
      uses: terraform-docs/gh-actions@main
      with:
        config-file: doc-gen/.terraform-docs.yml
        working-dir: terraform
        output-file: ../README.md
        output-format: markdown table
        git-push: false

    - name: Fix .git permissions
      run: sudo chmod -R ugo+rwX .git
    
    - name: Commit changes
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add visuals/terraform-graph.png
        git add README.md
        git diff-index --quiet HEAD || git commit -m "Update docs"
        git push
      shell: bash